/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppFilesRouteImport } from './routes/app.files'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as DesignIdRouteImport } from './routes/design.$id'
import { Route as DesignIdBBranchIdRouteImport } from './routes/design.$id_.b.$branchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const DesignIdRoute = DesignIdRouteImport.update({
  id: '/design/$id',
  path: '/design/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIdBBranchIdRoute = DesignIdBBranchIdRouteImport.update({
  id: '/design/$id_/b/$branchId',
  path: '/design/$id/b/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRoute
  '/app/files': typeof AppFilesRoute
  '/app/new': typeof AppNewRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/app/files': typeof AppFilesRoute
  '/app/new': typeof AppNewRoute
  '/design/$id': typeof DesignIdRoute
  '/app': typeof AppIndexRoute
  '/design/$id/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRoute
  '/app/files': typeof AppFilesRoute
  '/app/new': typeof AppNewRoute
  '/design/$id': typeof DesignIdRoute
  '/app/': typeof AppIndexRoute
  '/design/$id_/b/$branchId': typeof DesignIdBBranchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/settings'
    | '/app/files'
    | '/app/new'
    | '/design/$id'
    | '/app/'
    | '/design/$id/b/$branchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/app/files'
    | '/app/new'
    | '/design/$id'
    | '/app'
    | '/design/$id/b/$branchId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/settings'
    | '/app/files'
    | '/app/new'
    | '/design/$id'
    | '/app/'
    | '/design/$id_/b/$branchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  DesignIdRoute: typeof DesignIdRoute
  DesignIdBBranchIdRoute: typeof DesignIdBBranchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/design/$id': {
      id: '/design/$id'
      path: '/design/$id'
      fullPath: '/design/$id'
      preLoaderRoute: typeof DesignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$id_/b/$branchId': {
      id: '/design/$id_/b/$branchId'
      path: '/design/$id/b/$branchId'
      fullPath: '/design/$id/b/$branchId'
      preLoaderRoute: typeof DesignIdBBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppFilesRoute: typeof AppFilesRoute
  AppNewRoute: typeof AppNewRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFilesRoute: AppFilesRoute,
  AppNewRoute: AppNewRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SettingsRoute: SettingsRoute,
  DesignIdRoute: DesignIdRoute,
  DesignIdBBranchIdRoute: DesignIdBBranchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
