/**
 * Writes `src/migrations.gen.ts`: every migration's SQL as a string literal.
 *
 * The local server is compiled into one binary (`bun build --compile`), and a
 * compiled binary has no `drizzle/` folder beside it to read at start-up. The
 * migrations ride inside the code instead. Run after `db:generate`; the server
 * builds run it first, so a build never embeds a stale list.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')
const journal: {
  entries: ReadonlyArray<{ tag: string; when: number; breakpoints: boolean }>
} = JSON.parse(readFileSync(join(root, 'drizzle/meta/_journal.json'), 'utf8'))

const migrations = journal.entries.map((entry) => ({
  tag: entry.tag,
  when: entry.when,
  breakpoints: entry.breakpoints,
  sql: readFileSync(join(root, 'drizzle', `${entry.tag}.sql`), 'utf8'),
}))

writeFileSync(
  join(root, 'src/migrations.gen.ts'),
  `// Generated by scripts/embed-migrations.ts from drizzle/. Do not edit.
export const migrations: ReadonlyArray<{
  tag: string
  when: number
  breakpoints: boolean
  sql: string
}> = ${JSON.stringify(migrations, null, 2)}
`,
)
console.log(`embedded ${migrations.length} migrations`)
